// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/e-verify.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailVerifyRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerifyRequest) Reset()         { *m = EmailVerifyRequest{} }
func (m *EmailVerifyRequest) String() string { return proto.CompactTextString(m) }
func (*EmailVerifyRequest) ProtoMessage()    {}
func (*EmailVerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6060adeac1a878, []int{0}
}

func (m *EmailVerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerifyRequest.Unmarshal(m, b)
}
func (m *EmailVerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerifyRequest.Marshal(b, m, deterministic)
}
func (m *EmailVerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerifyRequest.Merge(m, src)
}
func (m *EmailVerifyRequest) XXX_Size() int {
	return xxx_messageInfo_EmailVerifyRequest.Size(m)
}
func (m *EmailVerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerifyRequest proto.InternalMessageInfo

func (m *EmailVerifyRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EmailVerifyResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailVerifyResponse) Reset()         { *m = EmailVerifyResponse{} }
func (m *EmailVerifyResponse) String() string { return proto.CompactTextString(m) }
func (*EmailVerifyResponse) ProtoMessage()    {}
func (*EmailVerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d6060adeac1a878, []int{1}
}

func (m *EmailVerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailVerifyResponse.Unmarshal(m, b)
}
func (m *EmailVerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailVerifyResponse.Marshal(b, m, deterministic)
}
func (m *EmailVerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailVerifyResponse.Merge(m, src)
}
func (m *EmailVerifyResponse) XXX_Size() int {
	return xxx_messageInfo_EmailVerifyResponse.Size(m)
}
func (m *EmailVerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailVerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmailVerifyResponse proto.InternalMessageInfo

func (m *EmailVerifyResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *EmailVerifyResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailVerifyRequest)(nil), "proto.EmailVerifyRequest")
	proto.RegisterType((*EmailVerifyResponse)(nil), "proto.EmailVerifyResponse")
}

func init() { proto.RegisterFile("proto/e-verify.proto", fileDescriptor_7d6060adeac1a878) }

var fileDescriptor_7d6060adeac1a878 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xd5, 0x2d, 0x4b, 0x2d, 0xca, 0x4c, 0xab, 0xd4, 0x03, 0x73, 0x85, 0x58, 0xc1,
	0x94, 0x92, 0x16, 0x97, 0x90, 0x6b, 0x6e, 0x62, 0x66, 0x4e, 0x18, 0x58, 0x2e, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x84, 0x8b, 0x35, 0x15, 0x24, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0xe1, 0x28, 0x39, 0x72, 0x09, 0xa3, 0xa8, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x05,
	0x29, 0x2e, 0x4b, 0xcc, 0xc9, 0x4c, 0x01, 0x2b, 0xe6, 0x08, 0x82, 0x70, 0xc0, 0x46, 0x14, 0x15,
	0xe5, 0x17, 0x49, 0x30, 0x41, 0x8d, 0x00, 0x71, 0x8c, 0x02, 0xb8, 0x78, 0x21, 0xba, 0x83, 0x53,
	0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xec, 0xb9, 0xd8, 0x20, 0x02, 0x42, 0x92, 0x10, 0x87, 0xe9,
	0x61, 0x3a, 0x47, 0x4a, 0x0a, 0x9b, 0x14, 0xc4, 0xf6, 0x24, 0x36, 0xb0, 0x94, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x27, 0xaa, 0x1d, 0xe0, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerifyServiceClient is the client API for VerifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerifyServiceClient interface {
	Verify(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*EmailVerifyResponse, error)
}

type verifyServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerifyServiceClient(cc *grpc.ClientConn) VerifyServiceClient {
	return &verifyServiceClient{cc}
}

func (c *verifyServiceClient) Verify(ctx context.Context, in *EmailVerifyRequest, opts ...grpc.CallOption) (*EmailVerifyResponse, error) {
	out := new(EmailVerifyResponse)
	err := c.cc.Invoke(ctx, "/proto.VerifyService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifyServiceServer is the server API for VerifyService service.
type VerifyServiceServer interface {
	Verify(context.Context, *EmailVerifyRequest) (*EmailVerifyResponse, error)
}

func RegisterVerifyServiceServer(s *grpc.Server, srv VerifyServiceServer) {
	s.RegisterService(&_VerifyService_serviceDesc, srv)
}

func _VerifyService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifyServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.VerifyService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifyServiceServer).Verify(ctx, req.(*EmailVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerifyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.VerifyService",
	HandlerType: (*VerifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _VerifyService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/e-verify.proto",
}
